export const copy = {
  en: {
    locale: 'en', direction: 'ltr', languageName: 'עברית', languagePath: '/he/',
    title: 'Port Manager — See what is happening on your Mac',
    description: 'A calm, local-first macOS utility that helps you understand what is running and act safely.',
    nav: ['How it helps', 'Safety', 'For advanced users'], download: 'Download for Mac', github: 'View on GitHub',
    eyebrow: 'A clearer local picture', hero: 'See what is happening on your Mac. Without guessing.',
    lead: 'Port Manager shows what is running in the background, what may be slowing you down, and what you can do safely — even if you do not use the Terminal.',
    trust: 'Runs locally · Keeps data private · Built for macOS',
    problemTitle: 'When your Mac stops making sense.',
    problems: [['An app will not start', 'See what is already using the space it needs.'], ['Your Mac feels slow', 'Understand what is asking for attention.'], ['An AI suggests a command', 'See the context before you approve an action.']],
    sections: [['See the story', 'Projects, apps, and background activity are shown together so you can understand the situation before you act.', 'projects'], ['Find the pressure', 'CPU, memory, energy, and storage become a clear picture instead of a collection of numbers.', 'resources'], ['Clear room carefully', 'Review developer clutter and move selected safe items to the Mac Trash after confirmation.', 'cache']],
    safetyTitle: 'Understand first. Act deliberately.', safety: ['Read-only, allowlist, and blocklist modes', 'Ownership checks before guarded actions', 'Critical macOS processes stay protected', 'Preview and explicit confirmation before meaningful changes'],
    aiTitle: 'For people who want a little more control.', aiLead: 'Port Manager also includes an MCP server for agent workflows. It remains optional, and the same safety layer applies.',
    setup: 'Copy MCP setup', copied: 'Copied', whyTitle: 'Local development got faster. Clarity did not.', why: 'Port Manager helps you understand your Mac before you start trying commands at random.',
    localTitle: 'Local-first by design.', local: 'The desktop app serves its interface only on a private loopback address. Your process information does not go to this website.',
    downloadTitle: 'Get a clearer local picture.', downloadLead: 'Choose the build for your Mac. On first launch, macOS may ask you to right-click and choose Open because releases are not yet notarized.',
    faqTitle: 'Questions, answered.',
    faqs: [['Does this work only on macOS?', 'Yes. Port Manager uses macOS system tools and ships as a Mac desktop app.'], ['Does it expose my computer to the network?', 'No. The local interface binds to 127.0.0.1 by default.'], ['Can it restart a process?', 'No. Restart-by-command remains intentionally disabled until a safe allowlist exists.']],
    privacy: 'Privacy', security: 'Security', releases: 'All releases', builtBy: 'A product by Bersaglio · Open source by Yonatan Gelfman',
    dialogTitle: 'Choose your Mac', dialogLead: 'Port Manager downloads are specific to your Mac type.', apple: 'Apple Silicon', appleNote: 'M1, M2, M3, M4, and newer', intel: 'Intel Mac', intelNote: 'Intel-based Mac computers', firstLaunch: 'First launch may require right-click → Open.', reject: 'Reject', accept: 'Accept analytics', consent: 'Analytics is used only with your permission to understand website use and improve downloads.', privacyTitle: 'Privacy and analytics', privacyLead: 'The Port Manager website uses Google Analytics 4 only after explicit consent.', privacyBody: 'Analytics may process basic website events such as page views and download choices. The desktop app stays local-first and does not send process data to this website.',
  },
  he: {
    locale: 'he', direction: 'rtl', languageName: 'English', languagePath: '/en/',
    title: 'Port Manager — להבין מה קורה ב־Mac שלך',
    description: 'כלי macOS רגוע ומקומי שעוזר להבין מה רץ ברקע ולפעול בבטחה.',
    nav: ['איך זה עוזר', 'בטיחות', 'למתקדמים'], download: 'הורד ל־Mac', github: 'צפה ב־GitHub',
    eyebrow: 'תמונה מקומית ברורה יותר', hero: 'הבן מה קורה ב־Mac שלך. בלי לנחש.',
    lead: 'Port Manager מציג בצורה ברורה מה פועל ברקע, מה מעכב אותך ומה אפשר לעשות בבטחה — גם בלי להכיר פקודות או פורטים.',
    trust: 'עובד מקומית · נשאר פרטי · נבנה ל־macOS',
    problemTitle: 'כשכבר לא ברור מה קורה ב־Mac.',
    problems: [['אפליקציה לא נפתחת', 'ראה מה כבר משתמש במה שהיא צריכה.'], ['ה־Mac מרגיש איטי', 'הבן מה באמת דורש תשומת לב.'], ['AI מציע פקודה', 'ראה את ההקשר לפני שמאשרים פעולה.']],
    sections: [['ראה את התמונה', 'פרויקטים, אפליקציות ופעילות ברקע מוצגים יחד כדי שתוכל להבין את המצב לפני שפועלים.', 'projects'], ['מצא את העומס', 'CPU, זיכרון, אנרגיה ואחסון הופכים לתמונה ברורה במקום לאוסף מספרים.', 'resources'], ['פנה מקום בזהירות', 'בדוק עומס פיתוח והעבר פריטים בטוחים שנבחרו לפח של ה־Mac לאחר אישור.', 'cache']],
    safetyTitle: 'קודם מבינים. ואז פועלים בכוונה.', safety: ['מצבי קריאה בלבד, allowlist ו־blocklist', 'בדיקת בעלות לפני פעולות מוגנות', 'תהליכי macOS קריטיים נשארים מוגנים', 'תצוגה מקדימה ואישור מפורש לפני שינוי משמעותי'],
    aiTitle: 'למי שרוצה עוד קצת שליטה.', aiLead: 'Port Manager כולל גם שרת MCP לזרימות עבודה עם סוכנים. זו יכולת אופציונלית, ואותה שכבת בטיחות נשארת פעילה.',
    setup: 'העתק הגדרת MCP', copied: 'הועתק', whyTitle: 'הפיתוח המקומי נהיה מהיר יותר. הבהירות לא.', why: 'Port Manager עוזר להבין את ה־Mac לפני שמתחילים לנסות פקודות באקראי.',
    localTitle: 'Local-first כברירת מחדל.', local: 'אפליקציית הדסקטופ מגישה את הממשק רק בכתובת loopback פרטית. מידע על התהליכים שלך לא נשלח לאתר הזה.',
    downloadTitle: 'קבל תמונה מקומית ברורה יותר.', downloadLead: 'בחר את ה־build המתאים ל־Mac שלך. בהפעלה הראשונה ייתכן שתידרש לחיצה ימנית → Open, כי ה־releases עדיין אינם Apple-notarized.',
    faqTitle: 'שאלות ותשובות.',
    faqs: [['Port Manager עובד רק על macOS?', 'כן. הוא משתמש בכלי המערכת של macOS ומופץ כאפליקציית desktop ל־Mac.'], ['האם הוא חושף את המחשב לרשת?', 'לא. הממשק המקומי נקשר כברירת מחדל ל־127.0.0.1.'], ['האם אפשר להפעיל מחדש תהליך?', 'לא. הפעלה מחדש באמצעות פקודה נשארת מושבתת בכוונה עד שתהיה allowlist בטוחה.']],
    privacy: 'פרטיות', security: 'אבטחה', releases: 'כל ה־releases', builtBy: 'מוצר מבית Bersaglio · קוד פתוח מאת Yonatan Gelfman',
    dialogTitle: 'בחר את סוג ה־Mac', dialogLead: 'ההורדה של Port Manager תלויה בסוג ה־Mac שלך.', apple: 'Apple Silicon', appleNote: 'M1, M2, M3, M4 ומעלה', intel: 'Mac עם Intel', intelNote: 'מחשבי Mac מבוססי Intel', firstLaunch: 'בהפעלה הראשונה ייתכן שתידרש לחיצה ימנית → Open.', reject: 'דחה', accept: 'אשר מדידה', consent: 'נשתמש במדידה רק באישורך כדי להבין שימוש באתר ולשפר את חוויית ההורדה.', privacyTitle: 'פרטיות ומדידה', privacyLead: 'אתר Port Manager משתמש ב־Google Analytics 4 רק לאחר הסכמה מפורשת.', privacyBody: 'Analytics עשוי לעבד אירועים בסיסיים כגון צפיות בעמוד ובחירת הורדה. אפליקציית הדסקטופ נשארת local-first ואינה שולחת נתוני תהליכים לאתר.',
  },
};
