export const copy = {
  en: {
    locale: 'en', direction: 'ltr', languageName: 'עברית', languagePath: '/he/',
    title: 'Port Manager — See what is happening on your Mac',
    description: 'A calm, local-first macOS utility that helps you understand what is running and act safely.',
    nav: ['How it helps', 'Safety', 'For advanced users'], download: 'Download for Mac', github: 'View on GitHub',
    eyebrow: 'A clearer local picture', hero: 'See what is happening on your Mac. Without guessing.',
    lead: 'Port Manager shows what is running in the background, what may be slowing you down, and what you can do safely — even if you do not use the Terminal.',
    trust: 'Runs locally · Keeps data private · Built for macOS',
    problemTitle: 'When your Mac stops making sense.',
    problems: [['An app will not start', 'See what is already using the space it needs.'], ['Your Mac feels slow', 'Understand what is asking for attention.'], ['An AI suggests a command', 'See the context before you approve an action.']],
    sections: [['See the story', 'Projects, apps, and background activity are shown together so you can understand the situation before you act.', 'projects'], ['Find the pressure', 'CPU, memory, energy, and storage become a clear picture instead of a collection of numbers.', 'resources'], ['Clear room carefully', 'Review developer clutter and move selected safe items to the Mac Trash after confirmation.', 'cache']],
    safetyTitle: 'Understand first. Act deliberately.', safety: ['Read-only, allowlist, and blocklist modes', 'Ownership checks before guarded actions', 'Critical macOS processes stay protected', 'Preview and explicit confirmation before meaningful changes'],
    aiTitle: 'For people who want a little more control.', aiLead: 'Port Manager also includes an MCP server for agent workflows. It remains optional, and the same safety layer applies.',
    setup: 'Copy MCP setup', copied: 'Copied', whyTitle: 'Local development got faster. Clarity did not.', why: 'Port Manager helps you understand your Mac before you start trying commands at random.',
    localTitle: 'Local-first by design.', local: 'The desktop app serves its interface only on a private loopback address. Your process information does not go to this website.',
    downloadTitle: 'Get a clearer local picture.', downloadLead: 'Choose the build for your Mac. On first launch, macOS may ask you to right-click and choose Open because releases are not yet notarized.',
    faqTitle: 'Questions, answered.',
    faqs: [['Does this work only on macOS?', 'Yes. Port Manager uses macOS system tools and ships as a Mac desktop app.'], ['Does it expose my computer to the network?', 'No. The local interface binds to 127.0.0.1 by default.'], ['Can it restart a process?', 'No. Restart-by-command remains intentionally disabled until a safe allowlist exists.']],
    privacy: 'Privacy', security: 'Security', releases: 'All releases', builtBy: 'A product by Bersaglio · Open source by Yonatan Gelfman',
    dialogTitle: 'Choose your Mac', dialogLead: 'Port Manager downloads are specific to your Mac type.', apple: 'Apple Silicon', appleNote: 'M1, M2, M3, M4, and newer', intel: 'Intel Mac', intelNote: 'Intel-based Mac computers', firstLaunch: 'First launch may require right-click → Open.', reject: 'Reject', accept: 'Accept analytics', consent: 'Analytics is used only with your permission to understand website use and improve downloads.', privacyTitle: 'Privacy and analytics', privacyLead: 'The Port Manager website uses Google Analytics 4 only after explicit consent.', privacyBody: 'Analytics may process basic website events such as page views and download choices. The desktop app stays local-first and does not send process data to this website.',
  },
  he: {
    locale: 'he', direction: 'rtl', languageName: 'English', languagePath: '/en/',
    title: 'Port Manager — בהירות מלאה לגבי מה שפועל ב־Mac שלך',
    description: 'כלי מקומי ל־macOS שמעניק תמונה ברורה של הפעילות במחשב ומאפשר לפעול בביטחון.',
    nav: ['איך זה עובד', 'בטיחות', 'למפתחים מתקדמים'], download: 'הורידו את Port Manager ל־Mac', github: 'צפייה ב־GitHub',
    eyebrow: 'שליטה שקטה בסביבה המקומית', hero: 'הבנה מלאה של מה שקורה ב־Mac שלך. בלי ניחושים.',
    lead: 'Port Manager מעניק תמונה ברורה של הפעילות במחשב שלך, מסייע לזהות מה מעכב אותך ומאפשר לפעול בביטחון — גם בלי להשתמש ב־Terminal.',
    trust: 'מקומי · פרטי · נבנה במיוחד ל־macOS',
    problemTitle: 'כשה־Mac דורש תשובה ברורה.',
    problems: [['אפליקציה לא עולה', 'גלו מה כבר תופס את המשאבים הדרושים לה.'], ['ה־Mac מאט', 'זהו במהירות אילו תהליכים דורשים תשומת לב.'], ['סוכן AI מציע פעולה', 'קבלו הקשר מלא לפני שמאשרים פעולה משמעותית.']],
    sections: [['תמונה אחת, מלאה', 'פרויקטים, אפליקציות ופעילות ברקע מוצגים יחד — כך שההחלטה מתקבלת מתוך הבנה, לא מתוך ניחוש.', 'projects'], ['לראות מה באמת מכביד', 'CPU, זיכרון, אנרגיה ואחסון הופכים לתמונה ברורה שאפשר להבין במבט אחד.', 'resources'], ['לפנות מקום בבטחה', 'סקירה מסודרת של עומסי פיתוח והעברה של פריטים מאושרים לפח של ה־Mac, רק לאחר אישור מפורש.', 'cache']],
    safetyTitle: 'מבינים את המצב. פועלים בביטחון.', safety: ['מצבי קריאה בלבד, רשימת אישור ורשימת חסימה', 'אימות בעלות לפני פעולות מוגנות', 'הגנה מובנית על תהליכי macOS חיוניים', 'תצוגה מקדימה ואישור מפורש לפני כל שינוי משמעותי'],
    aiTitle: 'כלי מתקדם, כשצריך.', aiLead: 'למפתחים העובדים עם סוכנים, Port Manager כולל גם שרת MCP. גם שם, אותן שכבות הגנה נשארות בתוקף.',
    setup: 'העתקת הגדרת MCP', copied: 'הועתק', whyTitle: 'הפיתוח המקומי התקדם. הבהירות נשארה מאחור.', why: 'Port Manager מחליף ניחושים בתמונה ברורה של מצב ה־Mac — לפני שמנסים פקודה נוספת.',
    localTitle: 'המידע נשאר אצלך.', local: 'הממשק פועל בכתובת loopback פרטית בלבד. מידע על התהליכים והפעילות במחשב שלך אינו נשלח לאתר.',
    downloadTitle: 'הגיע הזמן לראות את התמונה המלאה.', downloadLead: 'בחרו את הגרסה המתאימה ל־Mac שלכם. בהפעלה הראשונה ייתכן ש־macOS יבקש לבחור ב־Open באמצעות לחיצה ימנית, מאחר שההפצה עדיין אינה מאומתת ב־Apple.',
    faqTitle: 'שאלות ותשובות.',
    faqs: [['האם Port Manager זמין רק ל־macOS?', 'כן. Port Manager משתמש בכלי המערכת של macOS ומופץ כאפליקציית Mac ייעודית.'], ['האם Port Manager חושף את המחשב לרשת?', 'לא. הממשק המקומי פועל כברירת מחדל ב־127.0.0.1 בלבד.'], ['האם ניתן להפעיל מחדש תהליכים מתוך האפליקציה?', 'לא. הפעלה מחדש באמצעות פקודה מושבתת בכוונה, עד שתוגדר רשימת אישור בטוחה ומפורשת.']],
    privacy: 'פרטיות', security: 'אבטחה', releases: 'לכל הגרסאות', builtBy: 'Port Manager — מוצר מבית Bersaglio · קוד פתוח מאת Yonatan Gelfman',
    dialogTitle: 'בחרו את סוג ה־Mac', dialogLead: 'הורדת Port Manager מותאמת לארכיטקטורת ה־Mac שלכם.', apple: 'Apple Silicon', appleNote: 'M1, M2, M3, M4 ודגמים חדשים יותר', intel: 'Mac עם Intel', intelNote: 'מחשבי Mac מבוססי Intel', firstLaunch: 'בהפעלה הראשונה ייתכן שתידרש לחיצה ימנית ולאחריה בחירה ב־Open.', reject: 'דחייה', accept: 'אישור מדידה', consent: 'נשתמש במדידה רק בהסכמתך, כדי לשפר את חוויית האתר וההורדה.', privacyTitle: 'פרטיות ומדידה', privacyLead: 'אתר Port Manager משתמש ב־Google Analytics 4 רק לאחר הסכמה מפורשת.', privacyBody: 'המדידה עשויה לכלול אירועים בסיסיים, כגון צפייה בעמוד או בחירת הורדה. אפליקציית Port Manager נשארת מקומית ואינה שולחת נתוני תהליכים לאתר.',
  },
};
